
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - run: make install
      env:
        CI: true
    - name: build
      run: make build
    - name: Run linter
      run: make lint
    - run: make test
    - name: test & publish test coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.TEST_REPORTER_ID}}
      with:
        coverageCommand: make test-coverage
        debug: true

   
